---

- name: Create CaaS Directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: root
    group: root
  with_items:
    - "{{ service_containers_dir }}/{{ service.name }}/"
    - "{{ service_containers_dir }}/{{ service.name }}/scripts"
    - "{{ service_containers_dir }}/{{ service.name }}/volumes"
    - "{{ service_containers_dir }}/{{ service.name }}/volumes/etc-pihole"
    - "{{ service_containers_dir }}/{{ service.name }}/volumes/etc-dnsmasq.d"

- name: Template CaaS deployment files - servicectl.sh.j2
  ansible.builtin.template:
    src: servicectl.sh.j2
    dest: "{{ service_containers_dir }}/{{ service.name }}/scripts/servicectl.sh"
    owner: root
    group: root
    mode: 0755

- name: "Template CaaS deployment files - {{ service.name }}.service"
  ansible.builtin.template:
    src: service.j2
    dest: "/etc/systemd/system/{{ service.name }}.service"
    owner: root
    group: root
    mode: 0755
